language: minimal
sudo: required
env:
  matrix:
  - OS_VERSION=7 OSG_VERSION=3.5
  - OS_VERSION=8 OSG_VERSION=3.5

services:
  - docker

before_install:
  - sudo docker pull centos:centos${OS_VERSION}

script:
 # Run tests in Container
 - sudo docker run --rm=true -v `pwd`:/osg-configure:rw centos:centos${OS_VERSION} /bin/bash /osg-configure/tests/test_inside_docker.sh ${OS_VERSION} ${OSG_VERSION}

